<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPh7tqcp\Glpi_Kernel_KernelProductionDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPh7tqcp/Glpi_Kernel_KernelProductionDebugContainer.php') {
    touch(__DIR__.'/ContainerPh7tqcp.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelProductionDebugContainer::class, false)) {
    \class_alias(\ContainerPh7tqcp\Glpi_Kernel_KernelProductionDebugContainer::class, Glpi_Kernel_KernelProductionDebugContainer::class, false);
}

return new \ContainerPh7tqcp\Glpi_Kernel_KernelProductionDebugContainer([
    'container.build_hash' => 'Ph7tqcp',
    'container.build_id' => '2f583b1c',
    'container.build_time' => 1782877262,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPh7tqcp');
