<?php

namespace ContainerPh7tqcp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLDAPControllerService extends Glpi_Kernel_KernelProductionDebugContainer
{
    /**
     * Gets the public 'Glpi\Controller\Config\LDAPController' shared autowired service.
     *
     * @return \Glpi\Controller\Config\LDAPController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/src/Glpi/DependencyInjection/PublicService.php';
        include_once \dirname(__DIR__, 5).'/src/Glpi/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 5).'/src/Glpi/Controller/Config/LDAPController.php';

        return $container->services['Glpi\\Controller\\Config\\LDAPController'] = new \Glpi\Controller\Config\LDAPController();
    }
}
